#!/usr/bin/env ruby
#

$: << Dir.pwd + '/lib'

WEST_EU    = 'westeurope'
GROUP_NAME = 'masteriot'
IP         = 'pubip'
VM_NAME    = "#{GROUP_NAME}-vm"


require 'deploy'
require 'provision'
require 'yaml'

def action(arg)
    arg.to_sym
end

begin
    @conf = YAML::load(File.read('.config/configuration'))
rescue Exception => e
    raise 'unable to read file'
end

arg = ARGV[0]

usage = <<-EOT
    Basic tool testing azure ruby bindings:
    Usage:

        - deploy:  launch the application in AzureCloud
        - remove:  delete the application
        - status:  get the status of the application
        - install: perform the remote installation
        - update:  update your remote application

    examples:
            azptool deploy
            azptool install
            azptool run
EOT


init

case action(arg)
when :deploy
    deploy
when :remove
    delete_rs
when :status
    status
when :install
    provision(:install)
when :run
    provision(:run)
when :stop
    provision(:stop)
when :update
    provision(:update)
else
    STDOUT.print(usage)
end
